use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct ZgentSubagentModel {
    pub alias: String,
    pub description: String,
}

pub trait ZgentSubagentBridge {
    fn synchronize_allowed_models(&self, models: &[ZgentSubagentModel]) -> Result<()>;
}

pub fn write_subagent_models_toml(path: &Path, models: &[ZgentSubagentModel]) -> Result<()> {
    let mut content = String::from("# Generated by AgentHost for ZGent compatibility\n");
    for model in models {
        content.push_str("\n[[models]]\n");
        content.push_str(&format!("name = {:?}\n", model.alias));
        content.push_str(&format!("description = {:?}\n", model.description));
    }
    fs::write(path, content)?;
    Ok(())
}

pub fn prepare_subagent_models_file(
    server_root: &Path,
    models: &[ZgentSubagentModel],
) -> Result<Option<PathBuf>> {
    if models.is_empty() {
        return Ok(None);
    }
    let path = server_root.join("subagent-models.toml");
    write_subagent_models_toml(&path, models)
        .with_context(|| format!("failed to write {}", path.display()))?;
    Ok(Some(path))
}

#[cfg(test)]
mod tests {
    use super::{ZgentSubagentModel, prepare_subagent_models_file, write_subagent_models_toml};
    use tempfile::TempDir;

    #[test]
    fn writes_subagent_models_in_expected_toml_shape() {
        let temp_dir = TempDir::new().unwrap();
        let path = temp_dir.path().join("models.toml");
        write_subagent_models_toml(
            &path,
            &[ZgentSubagentModel {
                alias: "openai/gpt-5".to_string(),
                description: "General coding model".to_string(),
            }],
        )
        .unwrap();

        let rendered = std::fs::read_to_string(path).unwrap();
        assert!(rendered.contains("[[models]]"));
        assert!(rendered.contains("name = \"openai/gpt-5\""));
        assert!(rendered.contains("description = \"General coding model\""));
    }

    #[test]
    fn prepare_subagent_models_file_skips_empty_catalog() {
        let temp_dir = TempDir::new().unwrap();
        let path = prepare_subagent_models_file(temp_dir.path(), &[]).unwrap();
        assert!(path.is_none());
    }
}
